# A simple example of the conversation
# This information will be pass by the speech recognize API( text[i] = marker + r.recognize_google(audio[i]) )
# Note: recognize result from Google Speech API does not include any punctuation
text = []
text.append("")
text[0] = "[D] Hello Mr Potter could you please talk something about yourself" 
text.append("")
text[1] = "[P] Hello Dr Ingham I am Harry Potter a student 21 years old 170 centimeters height 65 kilograms weight Currently catched a cold"
text.append("")
text[2] = "[D] What are the symptoms that trouble you Specifically"
text.append("")
text[3] = "[P] I have been coughing for half a week and have been running a fever"
text.append("")
text[4] = "[D] I see and do you allergy to any kind of medicine"
text.append("")
text[5] = "[P] Might be Penicillins my former doctor told me don't use that"


# A sample keyword database
# The actual database should be generated by SQL or a Spider
keywordindex = ["Name", "Height", "Weight", "Billing", "Symptoms", "Allergy"]
keywordcategory = []
keywordcategory.append("")
keywordcategory[0] = {"am"}
keywordcategory.append("")
keywordcategory[1] = {"centimeter","centimeters","meter","meters","inch","inchs"}
keywordcategory.append("")
keywordcategory[2] = {"kilograms"}
keywordcategory.append("")
keywordcategory[3] = {"worker", "student" , "teacher"}
keywordcategory.append("")
keywordcategory[4] = {"cough", "coughed", "coughing", "fever", "ache", "itch"}
keywordcategory.append("")
keywordcategory[5] = {"penicillins" , "aspirins"}

# Splitting the text, and make the text not sensitive to the upper/lower cases
textsplit = []
for i in range (0, len(text)):
	text[i] = text[i].lower()
	textsplit.append(text[i].split())
	#print (textsplit[i])

# Analyzing the text (Keyword Comparing)
record = []

for i in range (0, len(textsplit)):
	for j in range (0, len(textsplit[i])):
		record.append([])
		for k in range (0, len(keywordcategory)):
			if textsplit[i][j] in keywordcategory[k] :
				if k >= 3 :
					record[k].append(textsplit[i][j])
				if k == 0 :
					record[k].append(textsplit[i][j+1])
				if k == 1 or k == 2:
					record[k].append(textsplit[i][j-1])
				

#Output the extracting results


for i in range (0, len(keywordcategory)):
	print (keywordindex[i])
	print (record[i])

